<a href="https://colab.research.google.com/github/akshar1277/Pytorch_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Thu Feb  1 17:45:48 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
print(torch.__version__)


2.1.0+cu121


**Instroduction to Tenasors **

Pytoroch tensors are created using torch.Tensor()

In [ ]:
# scalar
scalar=torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

In [ ]:
TENSOR[0][2]

tensor([2, 4, 5])

### Random tensors

why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`start with random numbers->look at data ->update randomm numbers->look at data->update random umber`

In [ ]:
# create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor



tensor([[0.3292, 0.3614, 0.3517, 0.2320],
        [0.9673, 0.2389, 0.5073, 0.7596],
        [0.7748, 0.3339, 0.7547, 0.1536]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor[0]

tensor([0.3292, 0.3614, 0.3517, 0.2320])

In [ ]:
random_tensor[1]

tensor([0.9673, 0.2389, 0.5073, 0.7596])

In [ ]:
random_tensor[2]

tensor([0.7748, 0.3339, 0.7547, 0.1536])

In [ ]:
# crate a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,colour channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# create a tensor of all zeros
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###Creating a range of tensor and tensors-like


In [ ]:
#use torch.range()
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# crating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:**Tensor datatypes is one of the 3 big errors you'll run into with pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [3]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,#what datatype is the tensor
                             device=None, # what device is your tensor on cpu or gpu
                             requires_grad=False #wheater or not to track gradieants

)
float_32_tensor

tensor([3., 6., 9.])

In [4]:

float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [5]:
 float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [6]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)